with-expecter: true
packages:
  github.com/AustralianCyberSecurityCentre/azul-backup.git/store:
    # place your package-specific config here
    config:
      inpackage: true
      dir: "{{.InterfaceDir}}"
    interfaces:
      # select the interfaces you want mocked
      StoreS3Interface:
        # Modify package-level config for this specific interface (if applicable)
        config:
          filename: store_mock.go
