// Code generated by mockery v2.53.5. DO NOT EDIT.

package store

import (
	minio "github.com/minio/minio-go/v7"
	mock "github.com/stretchr/testify/mock"
)

// MockStoreS3Interface is an autogenerated mock type for the StoreS3Interface type
type MockStoreS3Interface struct {
	mock.Mock
}

type MockStoreS3Interface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStoreS3Interface) EXPECT() *MockStoreS3Interface_Expecter {
	return &MockStoreS3Interface_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function with given fields: id
func (_m *MockStoreS3Interface) Delete(id string) (bool, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (bool, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStoreS3Interface_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockStoreS3Interface_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - id string
func (_e *MockStoreS3Interface_Expecter) Delete(id interface{}) *MockStoreS3Interface_Delete_Call {
	return &MockStoreS3Interface_Delete_Call{Call: _e.mock.On("Delete", id)}
}

func (_c *MockStoreS3Interface_Delete_Call) Run(run func(id string)) *MockStoreS3Interface_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockStoreS3Interface_Delete_Call) Return(_a0 bool, _a1 error) *MockStoreS3Interface_Delete_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStoreS3Interface_Delete_Call) RunAndReturn(run func(string) (bool, error)) *MockStoreS3Interface_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Exists provides a mock function with given fields: id
func (_m *MockStoreS3Interface) Exists(id string) (bool, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Exists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (bool, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStoreS3Interface_Exists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exists'
type MockStoreS3Interface_Exists_Call struct {
	*mock.Call
}

// Exists is a helper method to define mock.On call
//   - id string
func (_e *MockStoreS3Interface_Expecter) Exists(id interface{}) *MockStoreS3Interface_Exists_Call {
	return &MockStoreS3Interface_Exists_Call{Call: _e.mock.On("Exists", id)}
}

func (_c *MockStoreS3Interface_Exists_Call) Run(run func(id string)) *MockStoreS3Interface_Exists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockStoreS3Interface_Exists_Call) Return(_a0 bool, _a1 error) *MockStoreS3Interface_Exists_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStoreS3Interface_Exists_Call) RunAndReturn(run func(string) (bool, error)) *MockStoreS3Interface_Exists_Call {
	_c.Call.Return(run)
	return _c
}

// Fetch provides a mock function with given fields: id
func (_m *MockStoreS3Interface) Fetch(id string) ([]byte, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Fetch")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]byte, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) []byte); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStoreS3Interface_Fetch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Fetch'
type MockStoreS3Interface_Fetch_Call struct {
	*mock.Call
}

// Fetch is a helper method to define mock.On call
//   - id string
func (_e *MockStoreS3Interface_Expecter) Fetch(id interface{}) *MockStoreS3Interface_Fetch_Call {
	return &MockStoreS3Interface_Fetch_Call{Call: _e.mock.On("Fetch", id)}
}

func (_c *MockStoreS3Interface_Fetch_Call) Run(run func(id string)) *MockStoreS3Interface_Fetch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockStoreS3Interface_Fetch_Call) Return(_a0 []byte, _a1 error) *MockStoreS3Interface_Fetch_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStoreS3Interface_Fetch_Call) RunAndReturn(run func(string) ([]byte, error)) *MockStoreS3Interface_Fetch_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: options
func (_m *MockStoreS3Interface) List(options minio.ListObjectsOptions) <-chan minio.ObjectInfo {
	ret := _m.Called(options)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 <-chan minio.ObjectInfo
	if rf, ok := ret.Get(0).(func(minio.ListObjectsOptions) <-chan minio.ObjectInfo); ok {
		r0 = rf(options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan minio.ObjectInfo)
		}
	}

	return r0
}

// MockStoreS3Interface_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockStoreS3Interface_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - options minio.ListObjectsOptions
func (_e *MockStoreS3Interface_Expecter) List(options interface{}) *MockStoreS3Interface_List_Call {
	return &MockStoreS3Interface_List_Call{Call: _e.mock.On("List", options)}
}

func (_c *MockStoreS3Interface_List_Call) Run(run func(options minio.ListObjectsOptions)) *MockStoreS3Interface_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(minio.ListObjectsOptions))
	})
	return _c
}

func (_c *MockStoreS3Interface_List_Call) Return(_a0 <-chan minio.ObjectInfo) *MockStoreS3Interface_List_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStoreS3Interface_List_Call) RunAndReturn(run func(minio.ListObjectsOptions) <-chan minio.ObjectInfo) *MockStoreS3Interface_List_Call {
	_c.Call.Return(run)
	return _c
}

// Put provides a mock function with given fields: id, data
func (_m *MockStoreS3Interface) Put(id string, data []byte) error {
	ret := _m.Called(id, data)

	if len(ret) == 0 {
		panic("no return value specified for Put")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, []byte) error); ok {
		r0 = rf(id, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStoreS3Interface_Put_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Put'
type MockStoreS3Interface_Put_Call struct {
	*mock.Call
}

// Put is a helper method to define mock.On call
//   - id string
//   - data []byte
func (_e *MockStoreS3Interface_Expecter) Put(id interface{}, data interface{}) *MockStoreS3Interface_Put_Call {
	return &MockStoreS3Interface_Put_Call{Call: _e.mock.On("Put", id, data)}
}

func (_c *MockStoreS3Interface_Put_Call) Run(run func(id string, data []byte)) *MockStoreS3Interface_Put_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].([]byte))
	})
	return _c
}

func (_c *MockStoreS3Interface_Put_Call) Return(_a0 error) *MockStoreS3Interface_Put_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStoreS3Interface_Put_Call) RunAndReturn(run func(string, []byte) error) *MockStoreS3Interface_Put_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStoreS3Interface creates a new instance of MockStoreS3Interface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStoreS3Interface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStoreS3Interface {
	mock := &MockStoreS3Interface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
